/** @type {import('tailwindcss').Config} */
const withAlpha = (variable) => `rgb(var(--ctp-${variable}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        latte: {
          base: withAlpha("base"),
          mantle: withAlpha("mantle"),
          crust: withAlpha("crust"),
          text: withAlpha("text"),
          subtext1: withAlpha("subtext1"),
          subtext0: withAlpha("subtext0"),
          surface0: withAlpha("surface0"),
          surface1: withAlpha("surface1"),
          surface2: withAlpha("surface2"),
          overlay0: withAlpha("overlay0"),
          overlay1: withAlpha("overlay1"),
          overlay2: withAlpha("overlay2"),
          blue: withAlpha("blue"),
          lavender: withAlpha("lavender"),
          peach: withAlpha("peach"),
          red: withAlpha("red"),
          green: withAlpha("green"),
          yellow: withAlpha("yellow"),
          mauve: withAlpha("mauve"),
          maroon: withAlpha("maroon"),
        },
      },
      fontFamily: {
        display: ["Fraunces", "serif"],
        body: ["IBM Plex Sans", "sans-serif"],
        mono: [
          "IBM Plex Mono",
          "M PLUS 1 Code",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "monospace",
        ],
      },
      boxShadow: {
        "elev-1": "var(--shadow-elev-1)",
        "elev-2": "var(--shadow-elev-2)",
        "elev-3": "var(--shadow-elev-3)",
        "elev-4": "var(--shadow-elev-4)",
        "elev-5": "var(--shadow-elev-5)",
        "elev-6": "var(--shadow-elev-6)",
        "inner-soft": "var(--shadow-inner)",
        glass: "var(--shadow-glass)",
        glow: "var(--shadow-glow)",
        "accent-inset": "var(--shadow-accent-inset)",
        "accent-outline": "var(--shadow-accent-outline)",
        "accent-sm": "var(--shadow-accent-sm)",
        accent: "var(--shadow-accent)",
        "accent-lg": "var(--shadow-accent-lg)",
        "accent-panel": "var(--shadow-accent-panel)",
        "surface-hover": "var(--shadow-surface-hover)",
        modal: "var(--shadow-modal)",
        popover: "var(--shadow-popover)",
        "danger-outline": "var(--shadow-danger-outline)",
        "inner-highlight": "var(--shadow-inner-highlight)",
      },
    },
  },
  plugins: [],
};
