packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - msw

catalog:
  "@hono/node-server": "^1.19.4"
  "@hono/zod-validator": "^0.7.6"
  "execa": "^9.6.0"
  "hono": "^4.11.4"
  "qrcode-terminal": "^0.12.0"
  "web-push": "^3.6.7"
  "yaml": "^2.8.1"
  "zod": "^4.3.5"
