import { useEffect } from "react";

import {
  resetSessionFilesRefs,
  type ResetSessionFilesRefsInput,
  resetSessionFilesState,
  type ResetSessionFilesStateInput,
} from "./useSessionFiles-reset";

type UseSessionFilesContextResetEffectArgs = {
  paneId: string;
  repoRoot: string | null;
  worktreePath: string | null;
  loadTree: (targetPath: string) => Promise<unknown>;
} & ResetSessionFilesRefsInput &
  ResetSessionFilesStateInput;

export const useSessionFilesContextResetEffect = ({
  paneId,
  repoRoot,
  worktreePath,
  loadTree,
  treePageRequestMapRef,
  searchRequestMapRef,
  fileContentRequestMapRef,
  logReferenceLinkableCacheRef,
  logReferenceLinkableRequestMapRef,
  activeSearchRequestIdRef,
  activeFileContentRequestIdRef,
  activeLogResolveRequestIdRef,
  contextVersionRef,
  treePagesRef,
  fileModalCopyTimeoutRef,
  setSelectedFilePath,
  setExpandedDirSet,
  setSearchExpandedDirSet,
  setSearchCollapsedDirSet,
  setTreePages,
  setTreeLoadingByPath,
  setTreeError,
  setSearchQuery,
  setSearchResult,
  setSearchLoading,
  setSearchError,
  setSearchActiveIndex,
  setFileModalOpen,
  setFileModalPath,
  setFileModalLoading,
  setFileModalError,
  setFileModalFile,
  setFileModalMarkdownViewMode,
  setFileModalShowLineNumbers,
  setFileModalCopiedPath,
  setFileModalCopyError,
  setFileModalHighlightLine,
  setFileResolveError,
  setLogFileCandidateModalOpen,
  setLogFileCandidateReference,
  setLogFileCandidatePaneId,
  setLogFileCandidateLine,
  setLogFileCandidateItems,
}: UseSessionFilesContextResetEffectArgs) => {
  useEffect(() => {
    resetSessionFilesRefs({
      treePageRequestMapRef,
      searchRequestMapRef,
      fileContentRequestMapRef,
      logReferenceLinkableCacheRef,
      logReferenceLinkableRequestMapRef,
      activeSearchRequestIdRef,
      activeFileContentRequestIdRef,
      activeLogResolveRequestIdRef,
      contextVersionRef,
      treePagesRef,
      fileModalCopyTimeoutRef,
    });
    resetSessionFilesState({
      setSelectedFilePath,
      setExpandedDirSet,
      setSearchExpandedDirSet,
      setSearchCollapsedDirSet,
      setTreePages,
      setTreeLoadingByPath,
      setTreeError,
      setSearchQuery,
      setSearchResult,
      setSearchLoading,
      setSearchError,
      setSearchActiveIndex,
      setFileModalOpen,
      setFileModalPath,
      setFileModalLoading,
      setFileModalError,
      setFileModalFile,
      setFileModalMarkdownViewMode,
      setFileModalShowLineNumbers,
      setFileModalCopiedPath,
      setFileModalCopyError,
      setFileModalHighlightLine,
      setFileResolveError,
      setLogFileCandidateModalOpen,
      setLogFileCandidateReference,
      setLogFileCandidatePaneId,
      setLogFileCandidateLine,
      setLogFileCandidateItems,
    });

    if (!repoRoot) {
      return;
    }
    void loadTree(".");
  }, [
    activeFileContentRequestIdRef,
    activeLogResolveRequestIdRef,
    activeSearchRequestIdRef,
    contextVersionRef,
    fileContentRequestMapRef,
    fileModalCopyTimeoutRef,
    loadTree,
    logReferenceLinkableCacheRef,
    logReferenceLinkableRequestMapRef,
    paneId,
    repoRoot,
    worktreePath,
    searchRequestMapRef,
    setExpandedDirSet,
    setFileModalCopiedPath,
    setFileModalCopyError,
    setFileModalError,
    setFileModalFile,
    setFileModalHighlightLine,
    setFileModalLoading,
    setFileModalMarkdownViewMode,
    setFileModalOpen,
    setFileModalPath,
    setFileModalShowLineNumbers,
    setFileResolveError,
    setLogFileCandidateItems,
    setLogFileCandidateLine,
    setLogFileCandidateModalOpen,
    setLogFileCandidatePaneId,
    setLogFileCandidateReference,
    setSearchActiveIndex,
    setSearchCollapsedDirSet,
    setSearchError,
    setSearchExpandedDirSet,
    setSearchLoading,
    setSearchQuery,
    setSearchResult,
    setSelectedFilePath,
    setTreeError,
    setTreeLoadingByPath,
    setTreePages,
    treePageRequestMapRef,
    treePagesRef,
  ]);
};
