import { useMemo } from "react";

import type { SessionDetailViewProps } from "../SessionDetailView";
import {
  buildCommitSectionProps,
  buildDiffSectionProps,
  buildFileContentModalProps,
  buildFileNavigatorSectionProps,
  buildLogFileCandidateModalProps,
  buildLogModalProps,
  buildQuickPanelProps,
  buildScreenPanelProps,
  buildStateTimelineSectionProps,
} from "./section-props-builders";

export const useSessionDetailViewSectionProps = ({
  meta,
  sidebar,
  timeline,
  screen,
  controls,
  diffs,
  files,
  commits,
  logs,
  title,
  actions,
}: SessionDetailViewProps) => {
  const { paneId, session, nowMs, connectionIssue } = meta;
  const {
    sessionGroups,
    getRepoSortAnchorAt,
    connected,
    connectionIssue: sidebarConnectionIssue,
    requestStateTimeline,
    requestScreen,
    highlightCorrections,
    resolvedTheme,
  } = sidebar;
  const {
    timeline: stateTimeline,
    timelineRange,
    timelineError,
    timelineLoading,
    timelineExpanded,
    isMobile,
    setTimelineRange,
    toggleTimelineExpanded,
    refreshTimeline,
  } = timeline;
  const {
    mode,
    screenLines,
    imageBase64,
    fallbackReason,
    error,
    pollingPauseReason,
    contextLeftLabel,
    isScreenLoading,
    isAtBottom,
    handleAtBottomChange,
    handleUserScrollStateChange,
    forceFollow,
    scrollToBottom,
    handleModeChange,
    virtuosoRef,
    scrollerRef,
    handleRefreshScreen,
  } = screen;
  const {
    textInputRef,
    autoEnter,
    shiftHeld,
    ctrlHeld,
    controlsOpen,
    rawMode,
    allowDangerKeys,
    isSendingText,
    interactive,
    handleSendKey,
    handleSendText,
    handleUploadImage,
    handleRawBeforeInput,
    handleRawInput,
    handleRawKeyDown,
    handleRawCompositionStart,
    handleRawCompositionEnd,
    toggleAutoEnter,
    toggleControls,
    toggleShift,
    toggleCtrl,
    toggleRawMode,
    toggleAllowDangerKeys,
    handleTouchSession,
  } = controls;
  const {
    diffSummary,
    diffError,
    diffLoading,
    diffFiles,
    diffOpen,
    diffLoadingFiles,
    refreshDiff,
    toggleDiff,
  } = diffs;
  const {
    unavailable,
    selectedFilePath,
    searchQuery,
    searchActiveIndex,
    searchResult,
    searchLoading,
    searchError,
    searchMode,
    treeLoading,
    treeError,
    treeNodes,
    rootTreeHasMore,
    searchHasMore,
    fileModalOpen,
    fileModalPath,
    fileModalLoading,
    fileModalError,
    fileModalFile,
    fileModalMarkdownViewMode,
    fileModalShowLineNumbers,
    fileModalCopiedPath,
    fileModalCopyError,
    fileModalHighlightLine,
    fileResolveError,
    logFileCandidateModalOpen,
    logFileCandidateReference,
    logFileCandidateItems,
    onSearchQueryChange,
    onSearchMove,
    onSearchConfirm,
    onToggleDirectory,
    onSelectFile,
    onOpenFileModal,
    onCloseFileModal,
    onSetFileModalMarkdownViewMode,
    onToggleFileModalLineNumbers,
    onCopyFileModalPath,
    onResolveLogFileReference,
    onResolveLogFileReferenceCandidates,
    onSelectLogFileCandidate,
    onCloseLogFileCandidateModal,
    onLoadMoreTreeRoot,
    onLoadMoreSearch,
  } = files;
  const {
    commitLog,
    commitError,
    commitLoading,
    commitLoadingMore,
    commitHasMore,
    commitDetails,
    commitFileDetails,
    commitFileOpen,
    commitFileLoading,
    commitOpen,
    commitLoadingDetails,
    copiedHash,
    refreshCommitLog,
    loadMoreCommits,
    toggleCommit,
    toggleCommitFile,
    copyHash,
  } = commits;
  const {
    quickPanelOpen,
    logModalOpen,
    selectedSession,
    selectedLogLines,
    selectedLogLoading,
    selectedLogError,
    openLogModal,
    closeLogModal,
    toggleQuickPanel,
    closeQuickPanel,
  } = logs;
  const {
    titleDraft,
    titleEditing,
    titleSaving,
    titleError,
    openTitleEditor,
    closeTitleEditor,
    updateTitleDraft,
    saveTitle,
    resetTitle,
  } = title;
  const {
    handleFocusPane,
    handleTouchPane,
    handleTouchRepoPin,
    handleOpenPaneHere,
    handleOpenHere,
    handleOpenInNewTab,
  } = actions;

  const diffSectionProps = useMemo(
    () =>
      buildDiffSectionProps({
        diffSummary,
        diffError,
        diffLoading,
        diffFiles,
        diffOpen,
        diffLoadingFiles,
        refreshDiff,
        toggleDiff,
      }),
    [
      diffSummary,
      diffError,
      diffLoading,
      diffFiles,
      diffOpen,
      diffLoadingFiles,
      refreshDiff,
      toggleDiff,
    ],
  );

  const stateTimelineSectionProps = useMemo(
    () =>
      buildStateTimelineSectionProps({
        stateTimeline,
        timelineRange,
        timelineError,
        timelineLoading,
        timelineExpanded,
        isMobile,
        setTimelineRange,
        refreshTimeline,
        toggleTimelineExpanded,
      }),
    [
      stateTimeline,
      timelineRange,
      timelineError,
      timelineLoading,
      timelineExpanded,
      isMobile,
      setTimelineRange,
      refreshTimeline,
      toggleTimelineExpanded,
    ],
  );

  const commitSectionProps = useMemo(
    () =>
      buildCommitSectionProps({
        commitLog,
        commitError,
        commitLoading,
        commitLoadingMore,
        commitHasMore,
        commitDetails,
        commitFileDetails,
        commitFileOpen,
        commitFileLoading,
        commitOpen,
        commitLoadingDetails,
        copiedHash,
        refreshCommitLog,
        loadMoreCommits,
        toggleCommit,
        toggleCommitFile,
        copyHash,
      }),
    [
      commitLog,
      commitError,
      commitLoading,
      commitLoadingMore,
      commitHasMore,
      commitDetails,
      commitFileDetails,
      commitFileOpen,
      commitFileLoading,
      commitOpen,
      commitLoadingDetails,
      copiedHash,
      refreshCommitLog,
      loadMoreCommits,
      toggleCommit,
      toggleCommitFile,
      copyHash,
    ],
  );

  const fileNavigatorSectionProps = useMemo(
    () =>
      buildFileNavigatorSectionProps({
        unavailable,
        selectedFilePath,
        searchQuery,
        searchActiveIndex,
        searchResult,
        searchLoading,
        searchError,
        searchMode,
        treeLoading,
        treeError,
        treeNodes,
        rootTreeHasMore,
        searchHasMore,
        onSearchQueryChange,
        onSearchMove,
        onSearchConfirm,
        onToggleDirectory,
        onSelectFile,
        onOpenFileModal,
        onLoadMoreTreeRoot,
        onLoadMoreSearch,
      }),
    [
      unavailable,
      selectedFilePath,
      searchQuery,
      searchActiveIndex,
      searchResult,
      searchLoading,
      searchError,
      searchMode,
      treeLoading,
      treeError,
      treeNodes,
      rootTreeHasMore,
      searchHasMore,
      onSearchQueryChange,
      onSearchMove,
      onSearchConfirm,
      onToggleDirectory,
      onSelectFile,
      onOpenFileModal,
      onLoadMoreTreeRoot,
      onLoadMoreSearch,
    ],
  );

  const fileContentModalProps = useMemo(
    () =>
      buildFileContentModalProps({
        fileModalOpen,
        fileModalPath,
        fileModalLoading,
        fileModalError,
        fileModalFile,
        fileModalMarkdownViewMode,
        fileModalShowLineNumbers,
        fileModalCopiedPath,
        fileModalCopyError,
        fileModalHighlightLine,
        resolvedTheme,
        onCloseFileModal,
        onToggleFileModalLineNumbers,
        onCopyFileModalPath,
        onSetFileModalMarkdownViewMode,
      }),
    [
      fileModalOpen,
      fileModalPath,
      fileModalLoading,
      fileModalError,
      fileModalFile,
      fileModalMarkdownViewMode,
      fileModalShowLineNumbers,
      fileModalCopiedPath,
      fileModalCopyError,
      fileModalHighlightLine,
      resolvedTheme,
      onCloseFileModal,
      onToggleFileModalLineNumbers,
      onCopyFileModalPath,
      onSetFileModalMarkdownViewMode,
    ],
  );

  const screenPanelProps = useMemo(
    () =>
      buildScreenPanelProps({
        mode,
        connectionIssue,
        fallbackReason,
        error,
        pollingPauseReason,
        contextLeftLabel,
        isScreenLoading,
        imageBase64,
        screenLines,
        virtuosoRef,
        scrollerRef,
        isAtBottom,
        forceFollow,
        rawMode,
        allowDangerKeys,
        fileResolveError,
        handleModeChange,
        handleRefreshScreen,
        handleAtBottomChange,
        scrollToBottom,
        handleUserScrollStateChange,
        onResolveLogFileReference,
        onResolveLogFileReferenceCandidates,
        paneId,
        sourceRepoRoot: session?.repoRoot ?? null,
      }),
    [
      mode,
      connectionIssue,
      fallbackReason,
      error,
      pollingPauseReason,
      contextLeftLabel,
      isScreenLoading,
      imageBase64,
      screenLines,
      virtuosoRef,
      scrollerRef,
      isAtBottom,
      forceFollow,
      rawMode,
      allowDangerKeys,
      fileResolveError,
      handleModeChange,
      handleRefreshScreen,
      handleAtBottomChange,
      scrollToBottom,
      handleUserScrollStateChange,
      onResolveLogFileReference,
      onResolveLogFileReferenceCandidates,
      paneId,
      session?.repoRoot,
    ],
  );

  const quickPanelProps = useMemo(
    () =>
      buildQuickPanelProps({
        quickPanelOpen,
        sessionGroups,
        nowMs,
        paneId,
        openLogModal,
        handleOpenPaneHere,
        closeQuickPanel,
        toggleQuickPanel,
      }),
    [
      quickPanelOpen,
      sessionGroups,
      nowMs,
      paneId,
      openLogModal,
      handleOpenPaneHere,
      closeQuickPanel,
      toggleQuickPanel,
    ],
  );

  const logModalProps = useMemo(
    () =>
      buildLogModalProps({
        logModalOpen,
        selectedSession,
        selectedLogLines,
        selectedLogLoading,
        selectedLogError,
        closeLogModal,
        handleOpenHere,
        handleOpenInNewTab,
      }),
    [
      logModalOpen,
      selectedSession,
      selectedLogLines,
      selectedLogLoading,
      selectedLogError,
      closeLogModal,
      handleOpenHere,
      handleOpenInNewTab,
    ],
  );

  const logFileCandidateModalProps = useMemo(
    () =>
      buildLogFileCandidateModalProps({
        logFileCandidateModalOpen,
        logFileCandidateReference,
        logFileCandidateItems,
        onCloseLogFileCandidateModal,
        onSelectLogFileCandidate,
      }),
    [
      logFileCandidateModalOpen,
      logFileCandidateReference,
      logFileCandidateItems,
      onCloseLogFileCandidateModal,
      onSelectLogFileCandidate,
    ],
  );

  const sessionHeaderProps = useMemo(() => {
    if (!session) {
      return null;
    }
    return {
      state: {
        session,
        connectionIssue,
        nowMs,
        titleDraft,
        titleEditing,
        titleSaving,
        titleError,
      },
      actions: {
        onTitleDraftChange: updateTitleDraft,
        onTitleSave: saveTitle,
        onTitleReset: resetTitle,
        onOpenTitleEditor: openTitleEditor,
        onCloseTitleEditor: closeTitleEditor,
        onTouchSession: handleTouchSession,
      },
    };
  }, [
    session,
    connectionIssue,
    nowMs,
    titleDraft,
    titleEditing,
    titleSaving,
    titleError,
    updateTitleDraft,
    saveTitle,
    resetTitle,
    openTitleEditor,
    closeTitleEditor,
    handleTouchSession,
  ]);

  const sessionSidebarProps = useMemo(
    () => ({
      state: {
        sessionGroups,
        getRepoSortAnchorAt,
        nowMs,
        connected,
        connectionIssue: sidebarConnectionIssue,
        requestStateTimeline,
        requestScreen,
        highlightCorrections,
        resolvedTheme,
        currentPaneId: paneId,
        className: "border-latte-surface1/80 h-full w-full rounded-none rounded-r-3xl border-r",
      },
      actions: {
        onFocusPane: handleFocusPane,
        onTouchSession: handleTouchPane,
        onTouchRepoPin: handleTouchRepoPin,
      },
    }),
    [
      sessionGroups,
      getRepoSortAnchorAt,
      nowMs,
      connected,
      sidebarConnectionIssue,
      requestStateTimeline,
      requestScreen,
      highlightCorrections,
      resolvedTheme,
      paneId,
      handleFocusPane,
      handleTouchPane,
      handleTouchRepoPin,
    ],
  );

  const controlsPanelProps = useMemo(
    () => ({
      state: {
        interactive,
        textInputRef,
        autoEnter,
        controlsOpen,
        rawMode,
        allowDangerKeys,
        isSendingText,
        shiftHeld,
        ctrlHeld,
      },
      actions: {
        onSendText: handleSendText,
        onPickImage: handleUploadImage,
        onToggleAutoEnter: toggleAutoEnter,
        onToggleControls: toggleControls,
        onToggleRawMode: toggleRawMode,
        onToggleAllowDangerKeys: toggleAllowDangerKeys,
        onToggleShift: toggleShift,
        onToggleCtrl: toggleCtrl,
        onSendKey: handleSendKey,
        onRawBeforeInput: handleRawBeforeInput,
        onRawInput: handleRawInput,
        onRawKeyDown: handleRawKeyDown,
        onRawCompositionStart: handleRawCompositionStart,
        onRawCompositionEnd: handleRawCompositionEnd,
      },
    }),
    [
      interactive,
      textInputRef,
      autoEnter,
      controlsOpen,
      rawMode,
      allowDangerKeys,
      isSendingText,
      shiftHeld,
      ctrlHeld,
      handleSendText,
      handleUploadImage,
      toggleAutoEnter,
      toggleControls,
      toggleRawMode,
      toggleAllowDangerKeys,
      toggleShift,
      toggleCtrl,
      handleSendKey,
      handleRawBeforeInput,
      handleRawInput,
      handleRawKeyDown,
      handleRawCompositionStart,
      handleRawCompositionEnd,
    ],
  );

  return {
    diffSectionProps,
    fileNavigatorSectionProps,
    fileContentModalProps,
    commitSectionProps,
    screenPanelProps,
    stateTimelineSectionProps,
    quickPanelProps,
    logModalProps,
    logFileCandidateModalProps,
    sessionHeaderProps,
    sessionSidebarProps,
    controlsPanelProps,
  };
};
