import { useAtomValue } from "jotai";
import { useMemo } from "react";

import { useNowMs } from "@/lib/use-now-ms";

import { screenTextAtom } from "./atoms/screenAtoms";
import {
  connectedAtom,
  connectionIssueAtom,
  connectionStatusAtom,
  currentSessionAtom,
  fileNavigatorConfigAtom,
  highlightCorrectionsAtom,
  resolvedThemeAtom,
  sessionApiAtom,
  sessionsAtom,
} from "./atoms/sessionDetailAtoms";
import {
  buildActionsSection,
  buildLogsSection,
  buildTimelineSection,
  buildTitleSection,
} from "./hooks/session-detail-vm-section-builders";
import { useSessionCommits } from "./hooks/useSessionCommits";
import { useSessionDetailLayoutState } from "./hooks/useSessionDetailLayoutState";
import { useSessionDetailScreenControls } from "./hooks/useSessionDetailScreenControls";
import { useSessionDetailTimelineLogsActions } from "./hooks/useSessionDetailTimelineLogsActions";
import { useSessionDiffs } from "./hooks/useSessionDiffs";
import { useSessionFiles } from "./hooks/useSessionFiles";
import { useSessionRepoPins } from "./hooks/useSessionRepoPins";
import { useSessionTitleEditor } from "./hooks/useSessionTitleEditor";
import { extractCodexContextLeft } from "./sessionDetailUtils";

export const useSessionDetailVM = (paneId: string) => {
  const sessions = useAtomValue(sessionsAtom);
  const connected = useAtomValue(connectedAtom);
  const connectionStatus = useAtomValue(connectionStatusAtom);
  const connectionIssue = useAtomValue(connectionIssueAtom);
  const highlightCorrections = useAtomValue(highlightCorrectionsAtom);
  const fileNavigatorConfig = useAtomValue(fileNavigatorConfigAtom);
  const resolvedTheme = useAtomValue(resolvedThemeAtom);
  const session = useAtomValue(currentSessionAtom);
  const screenText = useAtomValue(screenTextAtom);
  const sessionApi = useAtomValue(sessionApiAtom);
  if (!sessionApi) {
    throw new Error("SessionDetailProvider is required");
  }
  const {
    requestCommitDetail,
    requestCommitFile,
    requestCommitLog,
    requestDiffFile,
    requestDiffSummary,
    requestRepoFileContent,
    requestRepoFileSearch,
    requestRepoFileTree,
    requestStateTimeline,
    requestScreen,
    focusPane,
    uploadImageAttachment,
    sendText,
    sendKeys,
    sendRaw,
    touchSession,
    updateSessionTitle,
  } = sessionApi;
  const nowMs = useNowMs();
  const { getRepoSortAnchorAt, paneRepoRootMap, touchRepoSortAnchor, sessionGroups } =
    useSessionRepoPins({
      sessions,
    });

  const {
    screen: {
      mode,
      screenLines,
      imageBase64,
      fallbackReason,
      error,
      setScreenError,
      isScreenLoading,
      pollingPauseReason,
      isAtBottom,
      handleAtBottomChange,
      handleUserScrollStateChange,
      forceFollow,
      scrollToBottom,
      handleModeChange,
      virtuosoRef,
      scrollerRef,
    },
    controls: {
      textInputRef,
      autoEnter,
      shiftHeld,
      ctrlHeld,
      controlsOpen,
      rawMode,
      allowDangerKeys,
      isSendingText,
      handleSendKey,
      handleSendText,
      handleUploadImage,
      handleRawBeforeInput,
      handleRawInput,
      handleRawKeyDown,
      handleRawCompositionStart,
      handleRawCompositionEnd,
      toggleAutoEnter,
      toggleControls,
      toggleShift,
      toggleCtrl,
      toggleRawMode,
      toggleAllowDangerKeys,
    },
    handleRefreshScreen,
  } = useSessionDetailScreenControls({
    paneId,
    connected,
    connectionIssue,
    requestScreen,
    sendText,
    sendKeys,
    sendRaw,
    uploadImageAttachment,
  });

  const {
    diffSummary,
    diffError,
    diffLoading,
    diffFiles,
    diffOpen,
    diffLoadingFiles,
    refreshDiff,
    toggleDiff,
  } = useSessionDiffs({
    paneId,
    connected,
    requestDiffSummary,
    requestDiffFile,
  });

  const {
    unavailable: filesUnavailable,
    selectedFilePath,
    searchQuery,
    searchActiveIndex,
    searchResult,
    searchLoading,
    searchError,
    searchMode,
    treeLoading,
    treeError,
    treeNodes,
    rootTreeHasMore,
    searchHasMore,
    fileModalOpen,
    fileModalPath,
    fileModalLoading,
    fileModalError,
    fileModalFile,
    fileModalMarkdownViewMode,
    fileModalShowLineNumbers,
    fileModalCopiedPath,
    fileModalCopyError,
    fileModalHighlightLine,
    fileResolveError,
    logFileCandidateModalOpen,
    logFileCandidateReference,
    logFileCandidatePaneId,
    logFileCandidateItems,
    onSearchQueryChange,
    onSearchMove,
    onSearchConfirm,
    onToggleDirectory,
    onSelectFile,
    onOpenFileModal,
    onCloseFileModal,
    onSetFileModalMarkdownViewMode,
    onToggleFileModalLineNumbers,
    onCopyFileModalPath,
    onResolveLogFileReference,
    onResolveLogFileReferenceCandidates,
    onSelectLogFileCandidate,
    onCloseLogFileCandidateModal,
    onLoadMoreTreeRoot,
    onLoadMoreSearch,
  } = useSessionFiles({
    paneId,
    repoRoot: session?.repoRoot ?? null,
    autoExpandMatchLimit: fileNavigatorConfig.autoExpandMatchLimit,
    requestRepoFileTree,
    requestRepoFileSearch,
    requestRepoFileContent,
  });

  const {
    commitLog,
    commitError,
    commitLoading,
    commitLoadingMore,
    commitHasMore,
    commitDetails,
    commitFileDetails,
    commitFileOpen,
    commitFileLoading,
    commitOpen,
    commitLoadingDetails,
    copiedHash,
    refreshCommitLog,
    loadMoreCommits,
    toggleCommit,
    toggleCommitFile,
    copyHash,
  } = useSessionCommits({
    paneId,
    connected,
    requestCommitLog,
    requestCommitDetail,
    requestCommitFile,
  });

  const currentRepoRoot = session?.repoRoot ?? null;
  const {
    timeline: {
      timeline,
      timelineRange,
      timelineError,
      timelineLoading,
      timelineExpanded,
      setTimelineRange,
      toggleTimelineExpanded,
      refreshTimeline,
    },
    logs: {
      quickPanelOpen,
      logModalOpen,
      selectedSession,
      selectedLogLines,
      selectedLogLoading,
      selectedLogError,
      openLogModal,
      closeLogModal,
      toggleQuickPanel,
      closeQuickPanel,
    },
    actions: {
      handleOpenInNewTab,
      handleFocusPane,
      handleOpenPaneHere,
      handleOpenHere,
      handleTouchRepoPin,
      handleTouchCurrentSession,
      handleTouchPaneWithRepoAnchor,
    },
  } = useSessionDetailTimelineLogsActions({
    paneId,
    connected,
    connectionIssue,
    requestScreen,
    requestStateTimeline,
    sessions,
    resolvedTheme,
    highlightCorrections,
    touchSession,
    focusPane,
    setScreenError,
    touchRepoSortAnchor,
    paneRepoRootMap,
    currentRepoRoot,
  });

  const {
    titleDraft,
    titleEditing,
    titleSaving,
    titleError,
    openTitleEditor,
    closeTitleEditor,
    updateTitleDraft,
    saveTitle,
    resetTitle,
  } = useSessionTitleEditor({
    session,
    paneId,
    updateSessionTitle,
  });

  const contextLeftLabel = useMemo(
    () => (session?.agent === "codex" ? extractCodexContextLeft(screenText) : null),
    [screenText, session?.agent],
  );
  const {
    is2xlUp,
    isMobile,
    sidebarWidth,
    handleSidebarPointerDown,
    detailSplitRatio,
    detailSplitRef,
    handleDetailSplitPointerDown,
  } = useSessionDetailLayoutState();

  return {
    meta: {
      paneId,
      session,
      nowMs,
      connected,
      connectionIssue,
    },
    sidebar: {
      sessionGroups,
      getRepoSortAnchorAt,
      connected,
      connectionIssue,
      requestStateTimeline,
      requestScreen,
      highlightCorrections,
      resolvedTheme,
    },
    layout: {
      is2xlUp,
      sidebarWidth,
      handleSidebarPointerDown,
      detailSplitRatio,
      detailSplitRef,
      handleDetailSplitPointerDown,
    },
    timeline: buildTimelineSection({
      timeline,
      timelineRange,
      timelineError,
      timelineLoading,
      timelineExpanded,
      isMobile,
      setTimelineRange,
      toggleTimelineExpanded,
      refreshTimeline,
    }),
    screen: {
      mode,
      screenLines,
      imageBase64,
      fallbackReason,
      error,
      pollingPauseReason,
      contextLeftLabel,
      isScreenLoading,
      isAtBottom,
      handleAtBottomChange,
      handleUserScrollStateChange,
      forceFollow,
      scrollToBottom,
      handleModeChange,
      virtuosoRef,
      scrollerRef,
      handleRefreshScreen,
    },
    controls: {
      interactive: connectionStatus !== "disconnected",
      textInputRef,
      autoEnter,
      shiftHeld,
      ctrlHeld,
      controlsOpen,
      rawMode,
      allowDangerKeys,
      isSendingText,
      handleSendKey,
      handleSendText,
      handleUploadImage,
      handleRawBeforeInput,
      handleRawInput,
      handleRawKeyDown,
      handleRawCompositionStart,
      handleRawCompositionEnd,
      toggleAutoEnter,
      toggleControls,
      toggleShift,
      toggleCtrl,
      toggleRawMode,
      toggleAllowDangerKeys,
      handleTouchSession: handleTouchCurrentSession,
    },
    diffs: {
      diffSummary,
      diffError,
      diffLoading,
      diffFiles,
      diffOpen,
      diffLoadingFiles,
      refreshDiff,
      toggleDiff,
    },
    files: {
      unavailable: filesUnavailable,
      selectedFilePath,
      searchQuery,
      searchActiveIndex,
      searchResult,
      searchLoading,
      searchError,
      searchMode,
      treeLoading,
      treeError,
      treeNodes,
      rootTreeHasMore,
      searchHasMore,
      fileModalOpen,
      fileModalPath,
      fileModalLoading,
      fileModalError,
      fileModalFile,
      fileModalMarkdownViewMode,
      fileModalShowLineNumbers,
      fileModalCopiedPath,
      fileModalCopyError,
      fileModalHighlightLine,
      fileResolveError,
      logFileCandidateModalOpen,
      logFileCandidateReference,
      logFileCandidatePaneId,
      logFileCandidateItems,
      onSearchQueryChange,
      onSearchMove,
      onSearchConfirm,
      onToggleDirectory,
      onSelectFile,
      onOpenFileModal,
      onCloseFileModal,
      onSetFileModalMarkdownViewMode,
      onToggleFileModalLineNumbers,
      onCopyFileModalPath,
      onResolveLogFileReference,
      onResolveLogFileReferenceCandidates,
      onSelectLogFileCandidate,
      onCloseLogFileCandidateModal,
      onLoadMoreTreeRoot,
      onLoadMoreSearch,
    },
    commits: {
      commitLog,
      commitError,
      commitLoading,
      commitLoadingMore,
      commitHasMore,
      commitDetails,
      commitFileDetails,
      commitFileOpen,
      commitFileLoading,
      commitOpen,
      commitLoadingDetails,
      copiedHash,
      refreshCommitLog,
      loadMoreCommits,
      toggleCommit,
      toggleCommitFile,
      copyHash,
    },
    logs: buildLogsSection({
      quickPanelOpen,
      logModalOpen,
      selectedSession,
      selectedLogLines,
      selectedLogLoading,
      selectedLogError,
      openLogModal,
      closeLogModal,
      toggleQuickPanel,
      closeQuickPanel,
    }),
    title: buildTitleSection({
      titleDraft,
      titleEditing,
      titleSaving,
      titleError,
      openTitleEditor,
      closeTitleEditor,
      updateTitleDraft,
      saveTitle,
      resetTitle,
    }),
    actions: buildActionsSection({
      handleFocusPane,
      handleTouchRepoPin,
      handleOpenPaneHere,
      handleOpenHere,
      handleOpenInNewTab,
      handleTouchPaneWithRepoAnchor,
    }),
  };
};

export type SessionDetailVM = ReturnType<typeof useSessionDetailVM>;
