import { useMemo } from "react";

import { usePushNotifications } from "@/features/notifications/use-push-notifications";

import { useSessionCommits } from "./hooks/useSessionCommits";
import { useSessionDetailLayoutState } from "./hooks/useSessionDetailLayoutState";
import { useSessionDetailScreenControls } from "./hooks/useSessionDetailScreenControls";
import { useSessionDetailTimelineLogsActions } from "./hooks/useSessionDetailTimelineLogsActions";
import { useSessionDetailVMState } from "./hooks/useSessionDetailVMState";
import { useSessionDiffs } from "./hooks/useSessionDiffs";
import { useSessionFiles } from "./hooks/useSessionFiles";
import { useSessionRepoNotes } from "./hooks/useSessionRepoNotes";
import { useSessionRepoPins } from "./hooks/useSessionRepoPins";
import { useSessionTitleEditor } from "./hooks/useSessionTitleEditor";
import { useSessionVirtualWorktree } from "./hooks/useSessionVirtualWorktree";
import { extractCodexContextLeft } from "./sessionDetailUtils";

export const useSessionDetailVM = (paneId: string) => {
  const pushNotifications = usePushNotifications({ paneId });

  const {
    sessions,
    connected,
    connectionStatus,
    connectionIssue,
    highlightCorrections,
    fileNavigatorConfig,
    launchConfig,
    resolvedTheme,
    session,
    screenText,
    nowMs,
    requestCommitDetail,
    requestCommitFile,
    requestCommitLog,
    requestWorktrees,
    requestDiffFile,
    requestDiffSummary,
    requestRepoNotes,
    requestRepoFileContent,
    requestRepoFileSearch,
    requestRepoFileTree,
    requestStateTimeline,
    requestScreen,
    focusPane,
    killPane,
    killWindow,
    refreshSessions,
    launchAgentInSession,
    uploadImageAttachment,
    sendText,
    sendKeys,
    sendRaw,
    touchSession,
    updateSessionTitle,
    createRepoNote,
    updateRepoNote,
    deleteRepoNote,
  } = useSessionDetailVMState(paneId);

  const { getRepoSortAnchorAt, paneRepoRootMap, touchRepoSortAnchor, sessionGroups } =
    useSessionRepoPins({
      sessions,
    });

  const {
    screen: {
      mode,
      wrapMode,
      screenLines,
      imageBase64,
      fallbackReason,
      error,
      setScreenError,
      isScreenLoading,
      pollingPauseReason,
      isAtBottom,
      handleAtBottomChange,
      handleUserScrollStateChange,
      forceFollow,
      scrollToBottom,
      handleModeChange,
      toggleWrapMode,
      virtuosoRef,
      scrollerRef,
    },
    controls: {
      textInputRef,
      autoEnter,
      shiftHeld,
      ctrlHeld,
      rawMode,
      allowDangerKeys,
      isSendingText,
      handleSendKey,
      handleKillPane,
      handleKillWindow,
      handleSendText,
      handleUploadImage,
      handleRawBeforeInput,
      handleRawInput,
      handleRawKeyDown,
      handleRawCompositionStart,
      handleRawCompositionEnd,
      toggleAutoEnter,
      toggleShift,
      toggleCtrl,
      toggleRawMode,
      toggleAllowDangerKeys,
    },
    handleRefreshScreen,
  } = useSessionDetailScreenControls({
    paneId,
    connected,
    connectionIssue,
    resolvedTheme,
    sessionAgent: session?.agent ?? null,
    highlightCorrections,
    requestScreen,
    sendText,
    sendKeys,
    sendRaw,
    killPane,
    killWindow,
    uploadImageAttachment,
  });

  const virtualWorktree = useSessionVirtualWorktree({
    paneId,
    session,
    requestWorktrees,
  });

  const diffs = useSessionDiffs({
    paneId,
    connected,
    worktreePath: virtualWorktree.effectiveWorktreePath,
    requestDiffSummary,
    requestDiffFile,
  });

  const files = useSessionFiles({
    paneId,
    repoRoot: session?.repoRoot ?? null,
    worktreePath: virtualWorktree.effectiveWorktreePath,
    autoExpandMatchLimit: fileNavigatorConfig.autoExpandMatchLimit,
    requestRepoFileTree,
    requestRepoFileSearch,
    requestRepoFileContent,
  });

  const commits = useSessionCommits({
    paneId,
    connected,
    worktreePath: virtualWorktree.effectiveWorktreePath,
    requestCommitLog,
    requestCommitDetail,
    requestCommitFile,
  });

  const currentRepoRoot = session?.repoRoot ?? null;
  const {
    notes,
    notesLoading,
    notesError,
    creatingNote,
    savingNoteId,
    deletingNoteId,
    refreshNotes,
    createNote,
    saveNote,
    removeNote,
  } = useSessionRepoNotes({
    paneId,
    repoRoot: currentRepoRoot,
    connected,
    requestRepoNotes,
    createRepoNote,
    updateRepoNote,
    deleteRepoNote,
  });

  const {
    timeline: {
      timeline,
      timelineScope,
      timelineRange,
      hasRepoTimeline,
      timelineError,
      timelineLoading,
      timelineExpanded,
      setTimelineScope,
      setTimelineRange,
      toggleTimelineExpanded,
      refreshTimeline,
    },
    logs: {
      quickPanelOpen,
      logModalOpen,
      selectedSession,
      selectedLogLines,
      selectedLogLoading,
      selectedLogError,
      openLogModal,
      closeLogModal,
      toggleQuickPanel,
      closeQuickPanel,
    },
    actions: {
      handleOpenPaneInNewWindow,
      handleOpenInNewTab,
      handleFocusPane,
      handleOpenPaneHere,
      handleOpenHere,
      handleTouchRepoPin,
      handleLaunchAgentInSession,
      handleTouchCurrentSession,
      handleTouchPaneWithRepoAnchor,
    },
  } = useSessionDetailTimelineLogsActions({
    paneId,
    connected,
    connectionIssue,
    requestScreen,
    requestStateTimeline,
    sessions,
    resolvedTheme,
    highlightCorrections,
    touchSession,
    focusPane,
    refreshSessions,
    launchAgentInSession,
    setScreenError,
    touchRepoSortAnchor,
    paneRepoRootMap,
    currentRepoRoot,
  });

  const {
    titleDraft,
    titleEditing,
    titleSaving,
    titleError,
    openTitleEditor,
    closeTitleEditor,
    updateTitleDraft,
    saveTitle,
    resetTitle,
  } = useSessionTitleEditor({
    session,
    paneId,
    updateSessionTitle,
  });

  const contextLeftLabel = useMemo(
    () => (session?.agent === "codex" ? extractCodexContextLeft(screenText) : null),
    [screenText, session?.agent],
  );
  const {
    is2xlUp,
    isMobile,
    sidebarWidth,
    handleSidebarPointerDown,
    detailSplitRatio,
    detailSplitRef,
    handleDetailSplitPointerDown,
  } = useSessionDetailLayoutState();

  return {
    meta: {
      paneId,
      session,
      nowMs,
      connected,
      connectionIssue,
    },
    sidebar: {
      sessionGroups,
      getRepoSortAnchorAt,
      connected,
      connectionIssue,
      launchConfig,
      requestWorktrees,
      requestStateTimeline,
      requestScreen,
      highlightCorrections,
      resolvedTheme,
    },
    layout: {
      is2xlUp,
      sidebarWidth,
      handleSidebarPointerDown,
      detailSplitRatio,
      detailSplitRef,
      handleDetailSplitPointerDown,
    },
    timeline: {
      timeline,
      timelineScope,
      timelineRange,
      hasRepoTimeline,
      timelineError,
      timelineLoading,
      timelineExpanded,
      isMobile,
      setTimelineScope,
      setTimelineRange,
      toggleTimelineExpanded,
      refreshTimeline,
    },
    screen: {
      mode,
      wrapMode,
      screenLines,
      imageBase64,
      fallbackReason,
      error,
      pollingPauseReason,
      contextLeftLabel,
      isScreenLoading,
      isAtBottom,
      handleAtBottomChange,
      handleUserScrollStateChange,
      forceFollow,
      scrollToBottom,
      handleModeChange,
      toggleWrapMode,
      virtuosoRef,
      scrollerRef,
      handleRefreshScreen,
      handleRefreshWorktrees: virtualWorktree.refreshWorktrees,
      effectiveBranch: virtualWorktree.effectiveBranch,
      effectiveWorktreePath: virtualWorktree.effectiveWorktreePath,
      worktreeRepoRoot: virtualWorktree.repoRoot,
      worktreeBaseBranch: virtualWorktree.baseBranch,
      worktreeSelectorEnabled: virtualWorktree.selectorEnabled,
      worktreeSelectorLoading: virtualWorktree.loading,
      worktreeSelectorError: virtualWorktree.error,
      worktreeEntries: virtualWorktree.entries,
      actualWorktreePath: virtualWorktree.actualWorktreePath,
      virtualWorktreePath: virtualWorktree.virtualWorktreePath,
      selectVirtualWorktree: virtualWorktree.selectVirtualWorktree,
      clearVirtualWorktree: virtualWorktree.clearVirtualWorktree,
      notificationStatus: pushNotifications.status,
      notificationPushEnabled: pushNotifications.pushEnabled,
      notificationSubscribed: pushNotifications.isSubscribed,
      notificationPaneEnabled: pushNotifications.isPaneEnabled,
      requestNotificationPermission: pushNotifications.requestPermissionAndSubscribe,
      togglePaneNotification: pushNotifications.togglePaneEnabled,
    },
    controls: {
      interactive: connectionStatus !== "disconnected",
      textInputRef,
      autoEnter,
      shiftHeld,
      ctrlHeld,
      rawMode,
      allowDangerKeys,
      isSendingText,
      handleSendKey,
      handleKillPane,
      handleKillWindow,
      handleSendText,
      handleUploadImage,
      handleRawBeforeInput,
      handleRawInput,
      handleRawKeyDown,
      handleRawCompositionStart,
      handleRawCompositionEnd,
      toggleAutoEnter,
      toggleShift,
      toggleCtrl,
      toggleRawMode,
      toggleAllowDangerKeys,
      handleTouchSession: handleTouchCurrentSession,
    },
    diffs,
    files,
    commits,
    notes: {
      repoRoot: currentRepoRoot,
      notes,
      notesLoading,
      notesError,
      creatingNote,
      savingNoteId,
      deletingNoteId,
      refreshNotes,
      createNote,
      saveNote,
      removeNote,
    },
    logs: {
      quickPanelOpen,
      logModalOpen,
      selectedSession,
      selectedLogLines,
      selectedLogLoading,
      selectedLogError,
      openLogModal,
      closeLogModal,
      toggleQuickPanel,
      closeQuickPanel,
    },
    title: {
      titleDraft,
      titleEditing,
      titleSaving,
      titleError,
      openTitleEditor,
      closeTitleEditor,
      updateTitleDraft,
      saveTitle,
      resetTitle,
    },
    actions: {
      handleFocusPane,
      handleTouchRepoPin,
      handleLaunchAgentInSession,
      handleOpenPaneHere,
      handleOpenPaneInNewWindow,
      handleOpenHere,
      handleOpenInNewTab,
      handleTouchPane: handleTouchPaneWithRepoAnchor,
    },
  };
};

export type SessionDetailVM = ReturnType<typeof useSessionDetailVM>;
