import type { PromptCompletionItem } from "@vde-monitor/shared";

// Keep this catalog aligned with the supported Codex CLI release when slash commands change.
const CODEX_COMMANDS = [
  ["permissions", "Set what Codex can do without asking first."],
  ["agent", "Switch the active agent thread."],
  ["subagents", "Switch the active agent thread."],
  ["apps", "Browse apps and insert one into the prompt."],
  ["plugins", "Browse and manage plugins."],
  ["hooks", "View and manage lifecycle hooks."],
  ["clear", "Clear the terminal and start a fresh task."],
  ["rename", "Rename the current task."],
  ["archive", "Archive the current session and exit Codex."],
  ["delete", "Permanently delete the current session and exit Codex."],
  ["compact", "Summarize the conversation to free context."],
  ["copy", "Copy the latest completed response."],
  ["diff", "Show the current Git diff."],
  ["experimental", "Toggle experimental features."],
  ["approve", "Approve one retry of a recent auto-review denial."],
  ["memories", "Configure memory use and generation."],
  ["skills", "Browse and use skills."],
  ["import", "Import supported Claude Code configuration."],
  ["feedback", "Send feedback and diagnostics."],
  ["init", "Generate an AGENTS.md scaffold."],
  ["logout", "Sign out of Codex."],
  ["mcp", "List configured MCP tools."],
  ["mention", "Attach a file to the conversation."],
  ["model", "Choose the active model and reasoning effort."],
  ["fast", "Toggle the Fast service tier."],
  ["plan", "Switch to plan mode."],
  ["goal", "Set or view the current task goal."],
  ["personality", "Choose a communication style."],
  ["ps", "Show background terminals."],
  ["stop", "Stop all background terminals."],
  ["fork", "Fork the current conversation."],
  ["app", "Continue the session in the desktop app."],
  ["side", "Start an ephemeral side conversation."],
  ["btw", "Start an ephemeral side conversation."],
  ["raw", "Toggle raw scrollback mode."],
  ["resume", "Resume a saved conversation."],
  ["new", "Start a new conversation."],
  ["quit", "Exit Codex."],
  ["exit", "Exit Codex."],
  ["review", "Review the current working tree."],
  ["status", "Show session configuration and token usage."],
  ["usage", "Show account token usage."],
  ["debug-config", "Inspect configuration layers and requirements."],
  ["statusline", "Configure status-line fields."],
  ["title", "Configure terminal title fields."],
  ["theme", "Choose a syntax-highlighting theme."],
  ["pets", "Choose or hide a terminal pet."],
  ["pet", "Choose or hide a terminal pet."],
] as const;

export const listCodexCommands = (): PromptCompletionItem[] =>
  CODEX_COMMANDS.map(([name, description]) => ({
    id: `codex-command:${name}`,
    label: `/${name}`,
    insertText: `/${name}`,
    description,
    argumentHint: "",
    kind: "command",
    scope: "built-in",
  }));
