import type { AgentMonitorConfigFile } from "./types";

export const allowedKeys = [
  "Enter",
  "Escape",
  "Tab",
  "BTab",
  "C-Tab",
  "C-BTab",
  "Space",
  "BSpace",
  "Up",
  "Down",
  "Left",
  "Right",
  "C-Up",
  "C-Down",
  "C-Left",
  "C-Right",
  "C-Enter",
  "C-Escape",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "C-a",
  "C-b",
  "C-c",
  "C-d",
  "C-e",
  "C-f",
  "C-g",
  "C-h",
  "C-i",
  "C-j",
  "C-k",
  "C-l",
  "C-m",
  "C-n",
  "C-o",
  "C-p",
  "C-q",
  "C-r",
  "C-s",
  "C-t",
  "C-u",
  "C-v",
  "C-w",
  "C-x",
  "C-y",
  "C-z",
  "C-\\",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
] as const;

export const defaultDangerKeys = ["C-c", "C-d", "C-z", "C-\\", "F12"];

export const defaultDangerCommandPatterns = [
  "rm\\s+(-rf?|--recursive)",
  "sudo\\s+rm",
  "mkfs",
  "dd\\s+if=",
  ">\\s*/dev/",
  "chmod\\s+777",
  "curl.*\\|\\s*(ba)?sh",
  "wget.*\\|\\s*(ba)?sh",
];

export const defaultConfig: AgentMonitorConfigFile = {
  bind: "127.0.0.1",
  port: 11080,
  allowedOrigins: [],
  rateLimit: {
    send: { windowMs: 1000, max: 10 },
    screen: { windowMs: 1000, max: 10 },
    raw: { windowMs: 1000, max: 200 },
  },
  dangerKeys: [...defaultDangerKeys],
  dangerCommandPatterns: [...defaultDangerCommandPatterns],
  activity: {
    pollIntervalMs: 1000,
    vwGhRefreshIntervalMs: 30_000,
    runningThresholdMs: 5000,
    inactiveThresholdMs: 60000,
  },
  hooks: {
    ttyCacheTtlMs: 60000,
    ttyCacheMax: 200,
  },
  input: { maxTextLength: 2000, enterKey: "C-m", enterDelayMs: 100 },
  screen: {
    mode: "text",
    defaultLines: 2000,
    maxLines: 2000,
    includeTruncated: false,
    joinLines: false,
    ansi: true,
    altScreen: "auto",
    highlightCorrection: {
      codex: true,
      claude: true,
    },
    image: {
      enabled: true,
      backend: "terminal",
      format: "png",
      cropPane: true,
      timeoutMs: 5000,
    },
  },
  logs: {
    maxPaneLogBytes: 2_000_000,
    maxEventLogBytes: 2_000_000,
    retainRotations: 5,
  },
  multiplexer: {
    backend: "tmux",
    wezterm: {
      cliPath: "wezterm",
      target: "auto",
    },
  },
  launch: {
    agents: {
      codex: { options: [] },
      claude: { options: [] },
    },
  },
  notifications: {
    pushEnabled: true,
    enabledEventTypes: ["pane.waiting_permission", "pane.task_completed"],
  },
  workspaceTabs: {
    displayMode: "all",
  },
  fileNavigator: {
    includeIgnoredPaths: [],
    autoExpandMatchLimit: 100,
  },
  tmux: {
    socketName: null,
    socketPath: null,
    primaryClient: null,
  },
};
