import type { AgentMonitorConfigFile } from "./types.js";

export const allowedKeys = [
  "Enter",
  "Escape",
  "Tab",
  "BTab",
  "C-Tab",
  "C-BTab",
  "Space",
  "BSpace",
  "Up",
  "Down",
  "Left",
  "Right",
  "C-Up",
  "C-Down",
  "C-Left",
  "C-Right",
  "C-Enter",
  "C-Escape",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "C-c",
  "C-d",
  "C-z",
  "C-\\",
  "C-u",
  "C-k",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
] as const;

export const defaultDangerKeys = ["C-c", "C-d", "C-z", "C-\\", "F12"];

export const defaultDangerCommandPatterns = [
  "rm\\s+(-rf?|--recursive)",
  "sudo\\s+rm",
  "mkfs",
  "dd\\s+if=",
  ">\\s*/dev/",
  "chmod\\s+777",
  "curl.*\\|\\s*(ba)?sh",
  "wget.*\\|\\s*(ba)?sh",
];

export const defaultConfig: AgentMonitorConfigFile = {
  bind: "127.0.0.1",
  port: 11080,
  readOnly: false,
  attachOnServe: true,
  staticAuth: false,
  allowedOrigins: [],
  rateLimit: {
    send: { windowMs: 1000, max: 10 },
    screen: { windowMs: 1000, max: 10 },
  },
  dangerKeys: [...defaultDangerKeys],
  dangerCommandPatterns: [...defaultDangerCommandPatterns],
  activity: {
    pollIntervalMs: 1000,
    runningThresholdMs: 15000,
    inactiveThresholdMs: 60000,
  },
  hooks: {
    ttyCacheTtlMs: 60000,
    ttyCacheMax: 200,
  },
  input: { maxTextLength: 2000, enterKey: "C-m", enterDelayMs: 100 },
  screen: {
    mode: "text",
    defaultLines: 2000,
    maxLines: 2000,
    joinLines: false,
    ansi: true,
    altScreen: "auto",
    image: {
      enabled: true,
      backend: "terminal",
      format: "png",
      cropPane: true,
      timeoutMs: 5000,
    },
  },
  logs: {
    maxPaneLogBytes: 2_000_000,
    maxEventLogBytes: 2_000_000,
    retainRotations: 5,
  },
  tmux: {
    socketName: null,
    socketPath: null,
    primaryClient: null,
  },
};
